services:
  boggle-frontend:
    build: 
      context: ./
      dockerfile: ./src/frontend/dockerfiles/Dockerfile.local
    container_name: boggle-app
    ports:
      - "5173:5173"
    volumes:
      - .:/boggle
      - /boggle/node_modules
    command: npm run dev
