version: "3.8"

services:
  boggle-frontend:
    build:
      context: ./ 
      dockerfile: ./src/frontend/dockerfiles/Dockerfile.prod
    container_name: boggle-app
    restart: always
    expose:
      - "80"    # port interne pour le proxy
    volumes:
      - .:/boggle
      - /boggle/node_modules
    networks:
      - web

networks:
  web:
    external: true
