services:
  boggle-frontend:
    build:
      context: ./
      dockerfile: ./src/frontend/dockerfiles/Dockerfile.prod
    container_name: boggle-app
    ports:
      - "8081:80"
    volumes:
      - .:/boggle
      - /boggle/node_modules
    restart: always